name: neversink
channels:
- conda-forge
- defaults
dependencies:
- python=3.*
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib=3.4.2
- pyyaml
- geopandas
- numpy=1.21.0
- scipy
- xarray
- netcdf4
- pandas=1.2.5
- gdal
- fiona
- rasterio>=1.0
- rasterstats
- shapely
- rtree
- pyproj>=2.0
- pyshp
- xlrd
- openpyxl
- requests